server:
  port: ${SERVER_PORT:0}
  shutdown: graceful
spring:
  application:
    name: ${APP_NAME:grocery-cart}
  profiles:
    active: ${ENV:dev}
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/grocery_cart}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      group-id: ${GROUP_ID:grocery-cart}
    topics:
      cart: ${CART_TOPIC:com.grocery.send.cart}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

grocery:
  client-uri:
    grocery-product: ${GROCERY_PRODUCT:http://grocery-product/api/internal/product}