server:
  port: ${SERVER_PORT:0}
  shutdown: graceful
spring:
  application:
    name: ${APP_NAME:grocery-cart}
  profiles:
    active: ${ENV:dev}
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/grocery_cart}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

grocery:
  client-uri:
    grocery-product: ${GROCERY_PRODUCT:http://grocery-product/api/internal/product}