spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          - gateway: TRACE
          - gateway:
              route:
                RouteDefinitionLocator: INFO

server:
  port: 8080