version: '3.2'

services:

  mysql-grocery-payment:
    image: mysql:latest
    ports:
      - 3000:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: thieunm
      MYSQL_PASSWORD: nmtkma0550
      MYSQL_DATABASE: grocery_payment
      MYSQL_ROOT_PASSWORD: nmtkma0550
    healthcheck:
      test: "exit 0"