server:
  port: ${SERVER_PORT:0}
  shutdown: graceful
spring:
  application:
    name: ${APP_NAME:grocery-product}
  profiles:
    active: ${ENV:dev}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/grocery_product
    username: root
    password: nmtkma0550
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      group-id: ${GROUP_ID:grocery-product}
    topics:
      product: ${PRODUCT_TOPIC:com.grocery.send.product}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

grocery:
  client-uri:
    grocery-payment: ${GROCERY_PAYMENT:http://grocery-payment/api/internal/bill}
