server:
  port: ${SERVER_PORT:0}
  shutdown: graceful
spring:
  application:
    name: ${APP_NAME:grocery-auth}
  profiles:
    active: ${ENV:dev}
  security:
    oauth2:
      client:
        registration:
          keycloak-login:
            clientId: grocery
            clientSecret: dqZTjIh9N2YHeDS7GbN7PYHLS4htglBH
            authorizationGrantType: password
            scope:
              - openid
              - profile
              - roles
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/grocery-realm
            token-uri: http://localhost:8180/realms/grocery-realm/protocol/openid-connect/token

keycloak:
  realm: grocery-realm
  resource: grocery
  auth-server-url: http://localhost:8180
  ssl-required: none
  use-resource-role-mappings: true
  bearer-only: true
  principal-attribute: preferred_username

keycloak-admin:
  username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  password: ${KEYCLOAK_ADMIN_PASSWORD:123456}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka